const trees = [
  'Dawn_redwood',
  'Maidenhair',
  'Shagbark_hickory',
  'Sugarberry',
  'White_oak',
  'Spindle_Bush',
  'White_Wax',
  'Winter_Flowering_Cherry',
  'Butterfly_Bush',
  'Mahonia_japonica',
  'soft_maple',
  'honey_locust',
  'cottonwood',
  'willow',
  'Douglas_fir',
  'Heather',
  'Lantern',
  'Witch_Hazel',
  'Camellia',
  'Rhododendron',
  'Lavender',
  'Artemisia',
  'Rosemary',
  'Sedum',
  'Annuals',
  'weeping_willow',
  'bald_cypress',
  'red_twig_dogwood',
  'river_birch',
  'red_chokeberry'
];

module.exports = trees;
